import React from "react";
import Link from "next/link";

import { LoginForm } from "@/components/LoginForm";
import { ToggleThemeMenu } from "@/components/ToggleThemeMenu";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | ChatApp",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <div className="flex flex-col h-screen ">
      <header className="fixed w-full h-16 flex justify-end items-center p-16">
        <ToggleThemeMenu />
      </header>

      <div className="w-full h-full flex justify-center items-center">
        <div className="w-[400px]">
          <div className="flex flex-col gap-2 mb-6">
            <h2 className="font-bold text-3xl">Welcome back</h2>
            <p className="font-base text-sm text-gray-600 dark:text-gray-300">
              Welcome back! To continue Log in to your account.
            </p>
          </div>

          <LoginForm />

          <div className="flex justify-center text-sm font-medium gap-1 mt-8">
            <p>Don&apos;t have a account?</p>

            <Link
              href="/register"
              className="underline text-black font-bold dark:text-white"
            >
              Create an account
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
